package txcheck

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	solanago "github.com/gagliardetto/solana-go"

	"github.com/botwallet-co/agent-cli/solana"
	"github.com/botwallet-co/agent-cli/solana/txcheck/txchecktest"
)

// packages/mcp and apps/sign implement the rules in the package comment as
// well. The vectors below are the messages all three must decide the same
// way: TestVectors writes them to testdata/vectors.json, and the other two
// run that file unchanged. In the Botwallet monorepo their copies must match
// it byte for byte. After changing a vector, rewrite the file and the copies
// with
//
//	go test ./solana/txcheck -run TestVectors -update

var update = flag.Bool("update", false, "rewrite testdata/vectors.json and its monorepo copies")

const vectorsFile = "testdata/vectors.json"

// monorepoRoot is the monorepo's root seen from this package
// (packages/cli-go/solana/txcheck), and monorepoCopies the copies under it.
const monorepoRoot = "../../../.."

var monorepoCopies = []string{
	"packages/mcp/tests/fixtures/txcheck-vectors.json",
	"apps/sign/tests/txcheck-vectors.json",
}

var vectorsAbout = []string{
	"Key 1 transaction check vectors. packages/cli-go (solana/txcheck), packages/mcp (src/solana/verify-transaction.ts)",
	"and apps/sign (src/lib/verify-transaction.ts) must each sign every message marked sign: true and refuse every other one.",
	"Generated by packages/cli-go with: go test ./solana/txcheck -run TestVectors -update. Do not edit by hand: that",
	"command also rewrites the copies in packages/mcp/tests/fixtures and apps/sign/tests, which must stay identical.",
	"message is a legacy Solana message in base64; network picks the USDC mint; amounts are USDC base units (6 decimals).",
}

// vector is one message and what the confirm response says it does.
type vector struct {
	name    string
	message func() []byte
	expect  func(e *Expectation) // changes to expectation()
	refused string               // "" means Key 1 signs; else part of the CLI's reason
}

// payment builds the server's message after edit changes the payment.
func payment(edit func(p *txchecktest.Payment)) func() []byte {
	return func() []byte {
		p := serverPayment()
		if edit != nil {
			edit(&p)
		}
		return txchecktest.BuildPayment(p).Bytes()
	}
}

// transfer is payment for the owner's signing page, which builds no fee
// transfer when there is no fee.
func transfer(edit func(p *txchecktest.Payment)) func() []byte {
	return func() []byte {
		p := serverPayment()
		if edit != nil {
			edit(&p)
		}
		return txchecktest.BuildTransfer(p).Bytes()
	}
}

// tampered builds the server's message for serverPayment, after base
// changes the payment, then edit changes the message itself.
func tampered(base func(p *txchecktest.Payment), edit func(m *txchecktest.Message)) func() []byte {
	return func() []byte {
		p := serverPayment()
		if base != nil {
			base(&p)
		}
		m := txchecktest.BuildPayment(p)
		edit(m)
		return m.Bytes()
	}
}

// devnet moves serverPayment to the devnet USDC mint.
func devnet(p *txchecktest.Payment) {
	p.Mint = devnetMint
	p.Source = txchecktest.ATA(p.Wallet, devnetMint)
	p.RecipientAccount = txchecktest.ATA(p.Recipient, devnetMint)
	p.FeeAccount = txchecktest.ATA(p.FeeCollection, devnetMint)
}

// x402 is what cmd's x402Intent reads from an x402 confirm response with
// these amount_usdc and fee_usdc, in base units.
func x402(amount, fee uint64) func(e *Expectation) {
	return func(e *Expectation) {
		e.MinAmount, e.MaxAmount, e.MaxFee = amount-9_999, amount, fee+10_000
	}
}

// web3Message was built independently with @solana/web3.js: 12.34 USDC from
// testKey("wallet"), a read-only signer, to testKey("recipient"), whose
// account it creates, and a 1.25 USDC fee.
const web3Message = "AgEFCjIYJXv6ZiMVoCnjNfVOKfwrxOUepKfvKJgCpB1a3mbc6NRAUIc9uoZap8Fwq0zOZNkIOaNNz9bPcdFOAgVEOxslBCvARGtDcahrNK8XS7WGKxc9yDRyUaa1PHZizVxFCTwZLzHExj2w4qvnFQWT5Kbt/JJsE5yiU9SNXGzbaapHrEy6550bCkKS4fZYBquOcY06+9lKC/GzFppnOpMvXC8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZdBpjbyPuVr8JcOk2c8oDYelhbeZkkPKYAj9AyWJdfjJclj04kifG7PRApFI4NgwtaE5na/xCEBI572Nvp+FnG+nrzvtutOj1l82qryXQxsbvkwtL24OR8pgIDRS9dYQbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpOVv3J/mqxegJEVkQc/z5yCb0KIBBMcoIm+ujhpQhdJoDBwYABAYIBQkBAQkDAwQBCQMgS7wAAAAAAAkDAwIBCQPQEhMAAAAAAA=="

func vectors() []vector {
	vs := []vector{
		// Shapes the server builds, today and before Oct 2026.
		{name: "payment, recipient and fee accounts open", message: payment(nil)},
		{name: "payment that opens the recipient's account", message: payment(func(p *txchecktest.Payment) {
			p.RecipientAccountExists = false
		})},
		{name: "payment that opens the fee account", message: payment(func(p *txchecktest.Payment) {
			p.FeeAccountExists = false
		})},
		{name: "payment that opens both accounts", message: payment(func(p *txchecktest.Payment) {
			p.RecipientAccountExists, p.FeeAccountExists = false, false
		})},
		{name: "payment with a zero fee transfer", message: payment(func(p *txchecktest.Payment) {
			p.Fee = 0
		}), expect: func(e *Expectation) { e.MaxFee = 0 }},
		{name: "payment with a fee below the quote", message: payment(func(p *txchecktest.Payment) {
			p.Fee = 240_000
		})},
		{name: "payment to the fee wallet itself", message: payment(func(p *txchecktest.Payment) {
			p.Recipient, p.RecipientAccount = feeCollection, txchecktest.ATA(feeCollection, mint)
			p.RecipientAccountExists, p.FeeAccountExists = false, false
		}), expect: func(e *Expectation) { e.Recipient = feeCollection }},
		{name: "withdrawal with the 3% fee and account setup", message: payment(func(p *txchecktest.Payment) {
			p.RecipientAccountExists, p.Fee = false, 550_000
		}), expect: func(e *Expectation) { e.MaxFee = 550_000 }},
		{name: "owner transfer with a fee", message: transfer(nil)},
		{name: "owner transfer without a fee", message: transfer(func(p *txchecktest.Payment) {
			p.Fee = 0
		}), expect: func(e *Expectation) { e.MaxFee = 0 }},
		{name: "owner transfer when the server collects no fee", message: transfer(func(p *txchecktest.Payment) {
			p.Fee = 0
		})},
		{name: "wallet as a read-only signer", message: tampered(nil, func(m *txchecktest.Message) {
			m.Header[1] = 1
		})},
		{name: "payment from a USDC account other than the wallet's associated one", message: payment(func(p *txchecktest.Payment) {
			p.Source = testKey("wallet's older USDC account")
		})},
		{name: "devnet payment", message: payment(devnet), expect: func(e *Expectation) { e.Mint = devnetMint }},
		{name: "x402 call at its exact price", message: payment(func(p *txchecktest.Payment) {
			p.Amount, p.Fee = 1_490_000, 10_000
		}), expect: x402(1_490_000, 10_000)},
		{name: "x402 call priced below the cent it is rounded up to", message: payment(func(p *txchecktest.Payment) {
			p.Amount, p.Fee = 9_995_001, 100_000
		}), expect: x402(10_000_000, 100_000)},
		{name: "x402 fee worked out on the exact price, above the quote (servers before Oct 2026)", message: payment(func(p *txchecktest.Payment) {
			p.Amount, p.Fee = 1_490_000, 14_900
		}), expect: x402(1_490_000, 10_000)},
		{name: "x402 call to a merchant with no USDC account", message: payment(func(p *txchecktest.Payment) {
			p.Amount, p.Fee, p.RecipientAccountExists = 1_000, 260_000, false
		}), expect: x402(10_000, 260_000)},
		{name: "message built by @solana/web3.js", message: func() []byte {
			b, err := base64.StdEncoding.DecodeString(web3Message)
			if err != nil {
				panic(err)
			}
			return b
		}, expect: func(e *Expectation) {
			e.Wallet, e.Recipient = testKey("wallet"), testKey("recipient")
			e.MinAmount, e.MaxAmount, e.MaxFee = 12_340_000, 12_340_000, 1_250_000
		}},

		// Payments that go somewhere else or move more.
		{name: "payment to another wallet's account", message: payment(func(p *txchecktest.Payment) {
			p.RecipientAccount = txchecktest.ATA(attacker, mint)
		}), refused: "not the USDC account of"},
		{name: "server shows one recipient, pays another", message: payment(func(p *txchecktest.Payment) {
			p.Recipient, p.RecipientAccount, p.RecipientAccountExists = attacker, txchecktest.ATA(attacker, mint), false
		}), refused: "not the USDC account of"},
		{name: "payment to another USDC account of the recipient", message: payment(func(p *txchecktest.Payment) {
			p.RecipientAccount = otherAccount
		}), refused: "token account " + otherAccount.String() + ", which is not the USDC account of"},
		{name: "devnet USDC on mainnet", message: payment(devnet), refused: "not the USDC account of"},
		{name: "amount above the one shown", message: payment(func(p *txchecktest.Payment) {
			p.Amount = 10_000_001
		}), refused: "pays 10.000001 USDC, not the 10.00 USDC shown"},
		{name: "amount below the one shown", message: payment(func(p *txchecktest.Payment) {
			p.Amount = 9_999_999
		}), refused: "not the 10.00 USDC shown"},
		{name: "x402 amount a cent below the one shown", message: payment(func(p *txchecktest.Payment) {
			p.Amount = 9_990_000
		}), expect: x402(10_000_000, 250_000), refused: "outside the 9.990001-10.00 USDC shown"},
		{name: "payment of 0 USDC", message: payment(func(p *txchecktest.Payment) {
			p.Amount = 0
		}), expect: func(e *Expectation) { e.MinAmount, e.MaxAmount = 0, 0 }, refused: "for 0 USDC"},
		{name: "fee a base unit above the quote", message: payment(func(p *txchecktest.Payment) {
			p.Fee = 250_001
		}), refused: "0.250001 USDC fee, more than the 0.25 USDC quoted"},
		{name: "fee far above the quote", message: payment(func(p *txchecktest.Payment) {
			p.Fee = 5_000_000
		}), refused: "5.00 USDC fee"},
		{name: "fee transfer when none was quoted", message: payment(nil), expect: func(e *Expectation) { e.MaxFee = 0 },
			refused: "more than the 0.00 USDC quoted"},
		{name: "x402 fee more than a cent above the quote", message: payment(func(p *txchecktest.Payment) {
			p.Amount, p.Fee = 1_490_000, 20_001
		}), expect: x402(1_490_000, 10_000), refused: "0.020001 USDC fee"},
		{name: "fee from another token account", message: tampered(nil, func(m *txchecktest.Message) {
			// One unit of another token the wallet holds (all of an NFT),
			// sent to someone else in the fee's place. Plain Transfer names
			// no mint, so only the source shows which token moves. (The
			// checks do not read which keys are writable, so the header stays.)
			other := testKey("another token")
			fee := &m.Instructions[1]
			m.Keys[fee.Accounts[1]] = txchecktest.ATA(attacker, other)
			fee.Accounts[0] = m.Index(txchecktest.ATA(wallet, other))
			fee.Data = txchecktest.TransferData(1)
		}), refused: "takes its fee from token account " + txchecktest.ATA(wallet, testKey("another token")).String()},
		{name: "fee transfer before the payment", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions[0], m.Instructions[1] = m.Instructions[1], m.Instructions[0]
		}), refused: "which is not the USDC account of " + recipient.String()},
		{name: "third transfer", message: tampered(nil, func(m *txchecktest.Message) {
			drain := m.Instructions[0]
			drain.Data = txchecktest.TransferData(1_000_000_000)
			m.Instructions = append(m.Instructions, drain)
		}), refused: "makes 3 transfers"},
		{name: "no transfer", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions = nil
		}), refused: "moves no USDC"},

		// Instructions a payment never has.
		{name: "token Approve", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions[0].Data = append([]byte{4}, m.Instructions[0].Data[1:]...)
		}), refused: "other than a transfer (instruction 4)"},
		{name: "token SetAuthority", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions = append(m.Instructions, txchecktest.Instruction{Program: m.Instructions[0].Program, Accounts: []uint8{2, 1}, Data: []byte{6, 2, 1}})
		}), refused: "(instruction 6)"},
		{name: "token CloseAccount", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions = append(m.Instructions, txchecktest.Instruction{Program: m.Instructions[0].Program, Accounts: []uint8{2, 4, 1}, Data: []byte{9}})
		}), refused: "(instruction 9)"},
		{name: "token Burn", message: tampered(nil, func(m *txchecktest.Message) {
			usdc := m.Index(mint)
			m.Header[2]++
			burn := make([]byte, 9)
			burn[0] = 8
			binary.LittleEndian.PutUint64(burn[1:], 1_000_000)
			m.Instructions = append(m.Instructions, txchecktest.Instruction{Program: m.Instructions[0].Program, Accounts: []uint8{2, usdc, 1}, Data: burn})
		}), refused: "(instruction 8)"},
		{name: "TransferChecked of USDC", message: tampered(nil, func(m *txchecktest.Message) {
			usdc := m.Index(mint)
			m.Header[2]++
			ix := &m.Instructions[0]
			ix.Accounts = []uint8{ix.Accounts[0], usdc, ix.Accounts[1], ix.Accounts[2]}
			ix.Data = txchecktest.TransferCheckedData(10_000_000, 6)
		}), refused: "(instruction 12)"},
		{name: "transfer authorized by the fee payer", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions[1].Accounts[2] = 0
		}), refused: "authorized by " + feePayer.String()},
		{name: "transfer from the wallet's own address", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions[0].Accounts[0] = 1
		}), refused: "own address as a token account"},
		{name: "fee to the wallet's own address", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions[1].Accounts[1] = 1
		}), refused: "own address as a token account"},
		{name: "System program transfer", message: tampered(nil, func(m *txchecktest.Message) {
			system := m.Index(solanago.SystemProgramID)
			m.Header[2]++
			m.Instructions = append(m.Instructions, txchecktest.Instruction{Program: system, Accounts: []uint8{1, 0}, Data: []byte{2, 0, 0, 0, 0, 0xca, 0x9a, 0x3b, 0, 0, 0, 0}})
		}), refused: "calls program 11111111111111111111111111111111"},
		{name: "memo", message: tampered(nil, func(m *txchecktest.Message) {
			memo := m.Index(memoProgram)
			m.Header[2]++
			m.Instructions = append(m.Instructions, txchecktest.Instruction{Program: memo, Data: []byte("hi")})
		}), refused: "calls program " + memoProgram.String()},
		{name: "Token-2022 transfer", message: tampered(nil, func(m *txchecktest.Message) {
			m.Keys[m.Instructions[0].Program] = token2022
		}), refused: "calls program " + token2022.String()},
		{name: "compute unit limit", message: tampered(nil, func(m *txchecktest.Message) {
			budget := m.Index(solanago.ComputeBudget)
			m.Header[2]++
			m.Instructions = append([]txchecktest.Instruction{{Program: budget, Data: []byte{2, 0x40, 0x0d, 0x03, 0x00}}}, m.Instructions...)
		}), refused: "calls program " + solanago.ComputeBudget.String()},
		{name: "compute unit price", message: tampered(nil, func(m *txchecktest.Message) {
			budget := m.Index(solanago.ComputeBudget)
			m.Header[2]++
			m.Instructions = append([]txchecktest.Instruction{{Program: budget, Data: []byte{3, 1, 0, 0, 0, 0, 0, 0, 0}}}, m.Instructions...)
		}), refused: "calls program " + solanago.ComputeBudget.String()},

		// Token account creations.
		{name: "creation paid by the wallet", message: tampered(func(p *txchecktest.Payment) {
			p.RecipientAccountExists = false
		}, func(m *txchecktest.Message) {
			m.Instructions[0].Accounts[0] = 1
		}), refused: "makes " + wallet.String() + " pay for a new token account"},
		{name: "creation for another mint", message: tampered(func(p *txchecktest.Payment) {
			p.RecipientAccountExists = false
		}, func(m *txchecktest.Message) {
			m.Keys[m.Instructions[0].Accounts[3]] = attacker
		}), refused: "for " + attacker.String() + ", not for USDC"},
		{name: "creation naming the wrong programs", message: tampered(func(p *txchecktest.Payment) {
			p.RecipientAccountExists = false
		}, func(m *txchecktest.Message) {
			m.Instructions[0].Accounts[4] = m.Instructions[0].Accounts[5]
		}), refused: "names the wrong programs"},
		{name: "creation of a non-associated account", message: tampered(func(p *txchecktest.Payment) {
			p.FeeAccountExists = false
		}, func(m *txchecktest.Message) {
			m.Instructions[0].Accounts[2] = m.Index(attacker)
			m.Header[2]++
		}), refused: "which is not the USDC account of " + attacker.String()},
		{name: "creation of the wallet's own USDC account", message: tampered(func(p *txchecktest.Payment) {
			p.FeeAccountExists = false
		}, func(m *txchecktest.Message) {
			m.Instructions[0].Accounts[1], m.Instructions[0].Accounts[2] = 2, 1
		}), refused: "creates a token account for this wallet"},
		{name: "creation of an account nothing is paid into", message: tampered(func(p *txchecktest.Payment) {
			p.RecipientAccountExists = false
		}, func(m *txchecktest.Message) {
			create := m.Instructions[0]
			create.Accounts = append([]uint8{}, create.Accounts...)
			create.Accounts[1], create.Accounts[2] = m.Index(txchecktest.ATA(attacker, mint)), m.Index(attacker)
			m.Header[2] += 2
			m.Instructions = append(m.Instructions, create)
		}), refused: "which none of its transfers pays into"},
		{name: "RecoverNested", message: tampered(func(p *txchecktest.Payment) {
			p.FeeAccountExists = false
		}, func(m *txchecktest.Message) {
			m.Instructions[0].Data = []byte{2}
		}), refused: "other than create"},
		{name: "three creations", message: tampered(func(p *txchecktest.Payment) {
			p.RecipientAccountExists, p.FeeAccountExists = false, false
		}, func(m *txchecktest.Message) {
			m.Instructions = append([]txchecktest.Instruction{m.Instructions[0]}, m.Instructions...)
		}), refused: "more than 2 token accounts"},

		// Signers.
		{name: "wallet pays the network fee", message: payment(func(p *txchecktest.Payment) {
			p.FeePayer = wallet
		}), refused: "makes this wallet pay the network fee"},
		{name: "another wallet's payment", message: payment(func(p *txchecktest.Payment) {
			p.Wallet = attacker
		}), refused: "signed by " + attacker.String()},
		{name: "three signers", message: tampered(nil, func(m *txchecktest.Message) {
			m.Header[0] = 3
		}), refused: "needs 3 signatures"},
		{name: "one signer", message: tampered(nil, func(m *txchecktest.Message) {
			m.Header[0] = 1
		}), refused: "needs 1 signatures"},
		{name: "both signers read-only", message: tampered(nil, func(m *txchecktest.Message) {
			m.Header[1] = 2
		}), refused: "header does not match"},

		// Malformed messages.
		{name: "versioned message", message: func() []byte {
			return append([]byte{0x80}, payment(nil)()...)
		}, refused: "versioned"},
		{name: "extra bytes", message: func() []byte {
			return append(payment(nil)(), 0)
		}, refused: "extra bytes"},
		{name: "cut short", message: func() []byte {
			b := payment(nil)()
			return b[:len(b)-1]
		}, refused: "cut short"},
		{name: "length not in its shortest form", message: func() []byte {
			// The account count, written in two bytes instead of one
			b := payment(nil)()
			return append(append(append([]byte{}, b[:3]...), b[3]|0x80, 0), b[4:]...)
		}, refused: "malformed length"},
		{name: "duplicate account", message: tampered(nil, func(m *txchecktest.Message) {
			m.Keys = append(m.Keys, m.Keys[3])
		}), refused: "listed twice"},
		{name: "header beyond the accounts", message: tampered(nil, func(m *txchecktest.Message) {
			m.Header[2] = byte(len(m.Keys))
		}), refused: "header does not match"},
		{name: "instruction pointing past the accounts", message: tampered(nil, func(m *txchecktest.Message) {
			m.Instructions[0].Accounts[1] = 200
		}), refused: "missing account"},
		{name: "empty", message: func() []byte { return nil }, refused: "cut short"},
	}
	return append(vs, serverShapes()...)
}

// serverShapes runs both server builders over every combination of open
// accounts, zero and non-zero fees, and a recipient that is the fee wallet.
// (The builders were checked byte for byte against the server's TypeScript
// for these combinations.) Combinations that give the same message are
// listed once.
func serverShapes() []vector {
	builders := []struct {
		name  string
		build func(txchecktest.Payment) *txchecktest.Message
	}{
		{"buildPaymentTransaction", txchecktest.BuildPayment},
		{"buildTransferTransaction", txchecktest.BuildTransfer},
	}
	openOrNew := map[bool]string{true: "open", false: "new"}
	var out []vector
	seen := map[string]bool{}
	for _, b := range builders {
		for _, toFeeWallet := range []bool{false, true} {
			for _, recipientOpen := range []bool{true, false} {
				for _, feeOpen := range []bool{true, false} {
					if toFeeWallet && feeOpen != recipientOpen {
						continue // one account cannot be both
					}
					for _, fee := range []uint64{250_000, 0} {
						p := serverPayment()
						p.RecipientAccountExists, p.FeeAccountExists, p.Fee = recipientOpen, feeOpen, fee
						if toFeeWallet {
							p.Recipient, p.RecipientAccount = feeCollection, p.FeeAccount
						}
						message := b.build(p).Bytes()
						if key := base64.StdEncoding.EncodeToString(message); seen[key] {
							continue
						} else {
							seen[key] = true
						}
						name := fmt.Sprintf("server shape: %s, fee %s USDC, recipient account %s", b.name, FormatUSDC(fee), openOrNew[recipientOpen])
						if !toFeeWallet {
							name += ", fee account " + openOrNew[feeOpen]
						} else {
							name += ", recipient is the fee wallet"
						}
						out = append(out, vector{name: name, message: func() []byte { return message }, expect: func(e *Expectation) {
							e.MaxFee = fee
							if toFeeWallet {
								e.Recipient = feeCollection
							}
						}})
					}
				}
			}
		}
	}
	return out
}

// vectorFile is the layout of testdata/vectors.json.
type vectorFile struct {
	About   []string     `json:"about"`
	Vectors []jsonVector `json:"vectors"`
}

type jsonVector struct {
	Name      string `json:"name"`
	Message   string `json:"message"`
	Wallet    string `json:"wallet"`
	Network   string `json:"network"`
	Recipient string `json:"recipient"`
	MinAmount uint64 `json:"min_amount,string"`
	MaxAmount uint64 `json:"max_amount,string"`
	MaxFee    uint64 `json:"max_fee,string"`
	Sign      bool   `json:"sign"`
}

// cluster is the network name the API reports for a USDC mint.
func cluster(m solanago.PublicKey) string {
	switch m.String() {
	case solana.USDCMintMainnet:
		return solana.ClusterMainnet
	case solana.USDCMintDevnet:
		return solana.ClusterDevnet
	}
	panic("no cluster for mint " + m.String())
}

func TestVectors(t *testing.T) {
	file := vectorFile{About: vectorsAbout}
	names := map[string]bool{}
	for _, v := range vectors() {
		if names[v.name] {
			t.Fatalf("two vectors are named %q", v.name)
		}
		names[v.name] = true
		exp := expectation()
		if v.expect != nil {
			v.expect(&exp)
		}
		message := v.message()

		// The CLI's own reason, which the shared file leaves out.
		checked, err := Verify(message, exp)
		switch {
		case v.refused == "" && err != nil:
			t.Errorf("%s: refused a message the server builds: %v", v.name, err)
		case v.refused == "" && (checked.Payment.Amount < exp.MinAmount || checked.Payment.Amount > exp.MaxAmount):
			t.Errorf("%s: Payment.Amount = %d", v.name, checked.Payment.Amount)
		case v.refused != "":
			var refused *RefusedError
			if !errors.As(err, &refused) {
				t.Errorf("%s: Verify = %v, %v; want a refusal containing %q", v.name, checked, err, v.refused)
			} else if !strings.Contains(refused.Reason, v.refused) {
				t.Errorf("%s: reason = %q, want it to contain %q", v.name, refused.Reason, v.refused)
			}
		}

		file.Vectors = append(file.Vectors, jsonVector{
			Name:      v.name,
			Message:   base64.StdEncoding.EncodeToString(message),
			Wallet:    exp.Wallet.String(),
			Network:   cluster(exp.Mint),
			Recipient: exp.Recipient.String(),
			MinAmount: exp.MinAmount,
			MaxAmount: exp.MaxAmount,
			MaxFee:    exp.MaxFee,
			Sign:      v.refused == "",
		})
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(file); err != nil {
		t.Fatal(err)
	}
	data := buf.Bytes()

	paths := []string{vectorsFile}
	if inMonorepo() {
		for _, c := range monorepoCopies {
			paths = append(paths, filepath.Join(monorepoRoot, filepath.FromSlash(c)))
		}
	}
	for _, path := range paths {
		if *update {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, data, 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		if got, err := os.ReadFile(path); err != nil || !bytes.Equal(got, data) {
			t.Errorf("%s does not match the vectors here (%v); rewrite it with: go test ./solana/txcheck -run TestVectors -update", path, err)
		}
	}

	// The file as the other two read it.
	var read vectorFile
	if err := json.Unmarshal(data, &read); err != nil {
		t.Fatal(err)
	}
	for _, v := range read.Vectors {
		message, err := base64.StdEncoding.DecodeString(v.Message)
		if err != nil {
			t.Fatalf("%s: %v", v.Name, err)
		}
		mintAddress, ok := solana.USDCMint(v.Network)
		if !ok {
			t.Fatalf("%s: network %q", v.Name, v.Network)
		}
		_, err = Verify(message, Expectation{
			Wallet:    solanago.MustPublicKeyFromBase58(v.Wallet),
			Mint:      solanago.MustPublicKeyFromBase58(mintAddress),
			Recipient: solanago.MustPublicKeyFromBase58(v.Recipient),
			MinAmount: v.MinAmount,
			MaxAmount: v.MaxAmount,
			MaxFee:    v.MaxFee,
		})
		if (err == nil) != v.Sign {
			t.Errorf("%s: sign = %v, Verify = %v", v.Name, v.Sign, err)
		}
	}
}

// inMonorepo reports whether this package sits in the Botwallet monorepo,
// next to the packages that keep copies of the vectors.
func inMonorepo() bool {
	here, err := os.Stat(".")
	if err != nil {
		return false
	}
	there, err := os.Stat(filepath.Join(monorepoRoot, "packages", "cli-go", "solana", "txcheck"))
	return err == nil && os.SameFile(here, there)
}
